# Create a VirtualService that injects delays and faults for the “backend” for these cases:

# A 5-second delay whenever a request is made to “backend.default.svc.cluster.local/delay”

# An HTTP 403 response whenever a request is made to “backend.default.svc.cluster.local/fault”
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-vs-delay
spec:
  hosts:
    - backend.default.svc.cluster.local
  http:
  - name: delay
    match:
      - uri:
          prefix: "/delay"
    route:
      - destination:
          host: backend.default.svc.cluster.local
    fault:
      delay:
        percentage:
            value: 100
        fixedDelay: 5s
  - name: fault
    match:
      - uri:
          prefix: "/fault"
    route:
      - destination:
          host: backend.default.svc.cluster.local
    fault:
      abort:
        percentage:
          value: 100
        httpStatus: 403