apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-ext-delay
spec:
  hosts:
    - httpbin.org
  http:
  - fault:
      delay:
        fixedDelay: 20s
        percentage:
          value: 100
    route:
      - destination:
          host: httpbin.org
        weight: 100